### PR TITLE
Added some documentation for Atari environments

### PR DESCRIPTION
**Pull request by Markus28**
Here is some preliminary documentation for a few Atari environments. There are a few things I am not sure about:
-  Should the wrapper `AtariEnv` be fully documented? I couldn't find any existing documentation regarding this wrapper and it seems that most documentation in this repository concentrates on instantiation via `gym.make`.
- I have not documented the `game` keyword argument of `AtariEnv`, since using this parameter would undermine the practice of registering different Atari games in gym (i.e., we could instantiate AirRaid by doing `gym.make("Asterix-v0", game="AirRaid")`, which would be weird). Is this the right approach?
- Is it a good idea to split the documentation into RAM and RGB versions? If I understand correctly, they only differ in the observation space. Moreover, there are also grayscale versions, which are currently only touched on very briefly.
- Should the reward dynamics of the environments be documented?
- Is it actually true that {0,..,**# Modes** -1} are the legal values for the `mode` keyword? I haven't found any official documentation for this behavior.

I hope this is more or less what you were expecting. I'm looking forward to your suggestions!

Best,
Markus

### CODE REVIEW

**Comment by Markus28** [comment]
I had completely overlooked that there are v4 and v5. Thanks for pointing this out! I have added a description of the different versions and registered configurations to atari.md.  
However, this leaves me wondering how I should best document the individual environments. It seems that having one article per configuration (i.e. for "-ram", "Deterministic", "Noframeskip" and any legal combination of those) would be impossible to maintain.
Should I just create one article per game (i.e. just "Alien-v5" for Alien) and then explain the effect of "-ram", "Deterministic", "Noframeskip" and "-vX" there?

**Comment by jkterry1** [comment]
"Should I just create one article per game (i.e. just "Alien-v5" for Alien) and then explain the effect of "-ram", "Deterministic", "Noframeskip" and "-vX" there?"

Yes

I'll have someone else respond to the other comments

**Comment by Rohan138** [comment]
1) For the ```AtariEnv``` wrapper: No, don't document the ```game``` keyword, it'd just lead to confusion with the gym API. Use one doc per game, then explain only the necessary keywords like the "Common Parameters" section from the [PettingZoo docs](https://github.com/Farama-Foundation/PettingZoo/blob/master/docs/atari.md)

2) Reward dynamics: I don't think you need to document the exact reward function, just the description and a link to the official AtariAge documentation. E.g. the PettingZoo docs for [Pong](https://github.com/Farama-Foundation/PettingZoo/blob/master/docs/atari/pong.md)
@jkterry1 want to weigh in on this?

3) The ```mode``` keyword: Yes.

**Comment by Markus28** [comment]
I added a description/link for the reward dynamics where possible.

**Comment by jkterry1** [comment]
@Markus28 this looks good, I'm going to merge it. Could you please create another PR adding individual docs for all the other Atari environmnets?

**Pull request merged**
