### PR TITLE
Update `toy_text`, `creating_environments`, `atari` docs

### PR DESCRIPTION
**Pull request by dtch1997**
This PR aims to implement: 
1) A generic README.md for `toy_text` environments. 
2) Update the `creating_environments.md` to a similar level of quality as https://www.pettingzoo.ml/environment_creation
3) A generic README.md for `atari-py` environments.

### CODE REVIEW

**Comment by dtch1997** [comment]
@jkterry1 I have started work on 1) and 2). 

For 1) it's a bit bare-bones at the moment as I wasn't really sure what you wanted or what could be said above what's already in the environment-specific READMEs. Please let me know if there is additional content I could add. 

For 2) did you want to keep on going with the abstract `FooEnv` example, or did you want to switch to a more concrete example such as (a minimally modified version of) one of the examples in `toy_text`?

**Comment by jkterry1** [comment]
My preference is FooEnv

**Comment by jkterry1** [comment]
I'll give these a read through in the morning, thanks a ton :)

**Comment by jkterry1** [comment]
@dtch1997 how goes the PR for the remaining atari environments?

**Comment by jkterry1** [comment]
Here, I'm going to go ahead and merge this, please create a separate PR for those

**Pull request merged**
