### PR TITLE
Added Centipede and ChopperCommand

### PR DESCRIPTION
**Pull request by Markus28**
New Atari environments

### CODE REVIEW

**Comment by Markus28** [comment]
There is a slight problem with Centipede:

```
gym.make("ALE/Centipede-v5", mode=0)
```
will give the following error:
```
RuntimeError: Invalid game mode requested
```
Only `mode=None` works. I was under the impression that `mode=0` is the default mode so what is going on here?

**Comment by JesseFarebro** [comment]
Sorry for the confusion, the default should be `mode=None`. Not every game has `mode=0`. This probably stems from my blog post where I had mistakenly written `mode=0` as being the default. Indeed the true default is `mode=None` as can be seen here:

https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/gym/envs/atari/environment.py#L28

Also, see this for more info: https://github.com/mgbellemare/Arcade-Learning-Environment/pull/237

**Comment by Markus28** [comment]
Thank you @JesseFarebro! It seems that, in particular, the set of valid modes is not necessarily of the form {0, ..., n}, is that right? Centipede, for instance, seems to allow the modes [22, 86].

**Comment by JesseFarebro** [comment]
That's correct. The reason why the modes look so odd is that those are the RAM values required to be set to be in that given mode. For example, in Centipede the check would look something like:

```py
# The memory address where the mode's value is stored
centipede_mode_memory_address = ...

# Set the mode
def setMode(mode):
    while readRAM(centipede_mode_memory_address) != mode:
        pressSelect()
```
as pressing select is how you cycle through the modes on the Atari 2600. It's a little more complicated than this but this is essentially how it's done. So in Centipede's case it supports two modes and we can detect whether we're in the right mode by checking if `readRAM(centipede_mode_memory_address) == 22` (for the first mode) or `readRAM(centipede_mode_memory_address) == 86` (for the second mode).

**Comment by benblack769** [comment]
@JesseFarebro One reason some of these game modes are odd is that they skip over multiplayer modes in some of these games. Not sure if it explains Centipede, but it explains other games like surround.

**Pull request merged**
