### PR TITLE
Alternative Structure

### PR DESCRIPTION
**Pull request by mgoulao**

### CODE REVIEW

**Comment by mgoulao** [comment]
@pseudo-rnd-thoughts, regarding the utils page, which is empty right now, what functions and classes do you want to add?

**Comment by trigaten** [comment]
Please resolve conflicts @mgoulao

**Comment by pseudo-rnd-thoughts** [comment]
@mgoulao play.py, save_video.py, step_api_compatibility.py, seeding.py and env_checker.py (with passive_env_checker.py).
most of these files have only one or two public functions. I think you can use autodoc for most of this. We can upgrade them if the docstrings not required enough

**Comment by mgoulao** [comment]
@pseudo-rnd-thoughts check if you agree with the final version of the utils.md file (the preview is missing some autodocs for some reason but it should be working)

**Comment by pseudo-rnd-thoughts** [comment]
Generally I think it is good. Looking through the whole website there is still a couple of sections that need updating
* spaces is missing `Sequence`, `Graph`, `Text` spaces
* vector is missing `gym.vector.make`

Otherwise, we need to update most of the docstrings. Do you know what proportion of the api reference uses AutoDocs compared to implementations

**Comment by mgoulao** [comment]
Ok, I will add those as well. 

Everything inside the API section in the sidebar uses AutoDocs. For the environments (except Atari), we use a script to obtain the docstrings (I'm still trying to figure out a better way).

**Pull request merged**
