### PR TITLE
Added my Custom Environment tutorial

### PR DESCRIPTION
**Pull request by GravermanDev**

### CODE REVIEW

**Comment by RedTachyon** [comment]
As I understand this is just self-promotion for a completely new video that wasn't discussed/requested earlier, which (from a cursory glance) itself has some bad practices w.r.t. the code? I think this can be closed.

**Comment by GravermanDev** [comment]
@RedTachyon You assume it was not discussed before when in fact I was asked to pull this request by PseudoRnd

**Comment by RedTachyon** [comment]
A PR description would be useful then. Point still stands that the tutorial doesn't follow best practices, so it can't be accepted.

**Comment by GravermanDev** [comment]
at least tell me what's so wrong about this tutorial that it can't be accepted and how can I fix it

**Comment by trigaten** [comment]
@GravermanDev Its awesome that you are into Gym and video development!

Here are a few concrete problems with the video:
* Lack of Pythonic variable names
* Using `random.randint` instead of `self.np_random`
* Not seeding the environment
* Ignoring the `return_info` argument in `reset` and ignoring metadata

Overall, the video is not quite up to the professional standards of the other tutorial/gym in general.

Keep learning and you'll get there :)

**Comment by GravermanDev** [comment]
@trigaten thanks for the feedback, I don't have much time right now but I will address those criticism and make another pull request with better video

**Pull request closed without merging**
