### PR TITLE
Adding individual Atari documentation

### PR DESCRIPTION
**Pull request by Markus28**
This pull request aims to document all individual Atari environments. This is still a WIP and I will continue adding new environments.

### CODE REVIEW

**Comment by Markus28** [comment]
Maybe it would also be a good idea to double check that everybody is happy with the current layout for the individual documentation pages. There are a lot of Atari environments and it would probably be painful to go through all of them to implement some change to the general layout.

**Comment by trigaten** [comment]
Try to follow the format of pendulum.md as noted in the README, specifically with the front matter.

**Comment by jkterry1** [comment]
@Markus28 two things:

1) We're trying to do a release of the website Monday (a week from today). Would you be able to finish the remaining environments by then?
2) Would you be able to message me on whatever platform we were using when we first got in touch (email, discord, etc.)? I seem to have lost you.

**Comment by jkterry1** [comment]
Hey, since there's so god damn many Atari environments, I'm going merge this to make coordination easier. Please create a PR with the next docs :)

**Comment by jkterry1** [comment]
@Markus28 one additional note- I'm going to start giving chunks of these to other people to do because there's so god damn many, for now I'm going to put you down for the boxing-chopper command chunk and we can revisit in the future

**Comment by trigaten** [comment]
@Markus28 How did you get an observation space of (250, 160, 3) rather than (210, 160, 3)?

**Comment by Markus28** [comment]
Hi, sorry, I somehow didn't get any notifications.
- @jkterry1 I just sent you an email :)
- @trigaten About the action space: There wasn't that much documentation to go off, so I simply tried it out for AirRaid. I assumed that it would be equivalent for all environments but I am just noticing that it isn't! Some environments also have the shape (214, 160, 3). I wasn't aware of that, I'll go back and fix those (if not already done).
- I finished 3 more environments. I'll check whether those were already taken care of, otherwise, I'll open a pull request 
- I was wondering whether there is some way to use some kind of templating procedure (like jinja). Maintaining all those pages individually seems quite tedious.

**Comment by trigaten** [comment]
@Markus28 Thanks,

We currently have a templating procedure for non-Atari environments: The docstring is pulled from gym and the front matter is all autogenerated. Check _scripts/gen_mds.py
Unfortunately, all Atari envs have the same docstring, so we cant autogen them as easily atm.

**Pull request merged**
