### PR TITLE
Reverted new render API

### PR DESCRIPTION
**Pull request by Markus28**
This PR reverts 2977d9e, d91549bd6c2b87e2562081cb6f5f4bb151e918b7 and 1fc72bb, which describe the new render API. This lead to a lot of confusion because the new render API is not released yet (see https://github.com/openai/gym/issues/2825, https://github.com/openai/gym/issues/2881 and the questions on discord). I think we should revert these changes for now and reapply them when the new release is out (I guess someone can just `git revert` this commit then). What do you think, @younik , @Pseudo-Rnd-Thoughts ?

Please don't merge until discussed with @younik.

### CODE REVIEW

**Comment by Markus28** [comment]
Also, once the new render API is released we should remember to update the code snippet on the landing page

**Comment by younik** [comment]
I absolutely agree, thanks for addressing it

**Comment by Markus28** [comment]
@younik this can be changed back now, right? Do you want to do the honors? (Also, there is no versioning for the docs yet, right?)

**Comment by younik** [comment]
@Markus28 done, thanks!

**Pull request merged**
