### PR TITLE
Atari stuff

### PR DESCRIPTION
**Pull request by RushivArora**
All the Atari notes from the PDF

### CODE REVIEW

**Comment by Markus28** [comment]
What's the motivation for using the term "option"? "Flavor" is the term that was established in one of the ALE papers.

**Comment by RushivArora** [comment]
> What's the motivation for using the term "option"? "Flavor" is the term that was established in one of the ALE papers.

The point regarding the wording "Flavor" was raised in a website review that @jkterry1 could comment on. The motivation with using the word "option" was to give a silent nod to Hierarchical Reinforcement Learning.

**Comment by Markus28** [comment]
Atari itself has nothing to do with hierarchical RL and the options framework though. I feel like we should stick with the established nomenclature.

**Comment by RushivArora** [comment]
Didn't realise flavor was official nomenclature since I was working off of the PDF reviewing the website. I can change it back to flavor in this case.

**Pull request merged**
